apiVersion: v1
kind: Service
metadata:
  name: {{ include "aoc-orchestration.fullname" . }}-broker-service
  namespace: {{ default .Release.Namespace .Values.global.namespaceOverride }}
  labels:
    {{- include "aoc-orchestration.labels" . | nindent 4 }}
    app.kubernetes.io/component: broker
spec:
  type: {{ .Values.broker.service.type }}
  ports:
    - port: {{ .Values.broker.service.port }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    {{- include "aoc-orchestration.broker.selectorLabels" . | nindent 4 }}