apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aoc-orchestration.fullname" . }}-config
  namespace: {{ default .Release.Namespace .Values.global.namespaceOverride }}
  labels:
    {{- include "aoc-orchestration.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.global.environment | quote }}
  LOG_LEVEL: {{ .Values.engine.env.logLevel | quote }}
  HEARTBEAT_INTERVAL: {{ .Values.engine.env.heartbeatInterval | quote }}