apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aoc-orchestration.fullname" . }}-secrets
  namespace: {{ default .Release.Namespace .Values.global.namespaceOverride }}
  labels:
    {{- include "aoc-orchestration.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.postgresPassword | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.user | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}