apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aoc-orchestration.fullname" . }}-servicemonitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: prometheus-stack
    {{- include "aoc-orchestration.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "aoc-orchestration.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s